title: Radio Mulhid
description: Free your mind from the chains of Islamic slavery
author: Hujjatul Murtadeen
email: exmuslimadamseeker@gmail.com
lang: hi-in
logo: /assets/img/logo.png
baseurl: "/YouTubeLive.html" # the subpath of your site, e.g. /blog
url: "adamseekeroftruth.com" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
